apiVersion: v1
kind: Pod
metadata:
    name: worker3-background
    namespace: trimaran-test
spec:
  containers:
  - name: stress-lowvar
    image: progrium/stress
    env:
    - name: CPU_LOAD
      value: "2"
    command: [sh, -c]
    args: ["stress -q -c $(CPU_LOAD)"]
    resources:
      requests:
        cpu: "2"
      limits:
        cpu: "4"
  nodeName: 10.242.64.6
