apiVersion: v1
kind: Pod
metadata:
    name: worker2-background
    namespace: trimaran-test
spec:
  containers:
  - name: stress
    image: progrium/stress
    env:
    - name: CPU_LOAD
      value: "5"
    - name: ON_DURATION
      value: "5m"
    - name: OFF_DURATION
      value: "5m"
    command: [sh, -c]
    args: ["while true; do stress -q -c $(CPU_LOAD) -t $(ON_DURATION); sleep $(OFF_DURATION); done"]
    resources:
      requests:
        cpu: "2"
      limits:
        cpu: "4"
  nodeName: 10.242.64.5
