apiVersion: v1
kind: Pod
metadata:
    name: test-pod
    namespace: trimaran-test
    labels:
      name: stress
spec:
  schedulerName: trimaran-scheduler
  containers:
  - name: stress
    image: progrium/stress
    env:
    - name: CPU_LOAD
      value: "2"
    - name: ON_DURATION
      value: "1m"
    - name: OFF_DURATION
      value: "5m"
    command: [sh, -c]
    args: ["while true; do stress -q -c $(CPU_LOAD) -t $(ON_DURATION); sleep $(OFF_DURATION); done"]
    resources:
      requests:
        cpu: "500m"
