{
 "title": "Trimaran - TargetLoadPacking Plugin Testing",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Total CPU Limit per Node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(node) (kube_pod_container_resource_limits{resource=\"cpu\"})",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Total CPU Request per Node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(node) (kube_pod_container_resource_requests{resource=\"cpu\"})",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Total CPU Allocatable per Node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(node) (kube_node_status_allocatable{resource=\"cpu\"})",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "CPU Usage Ratio on Nodes",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "instance:node_cpu:ratio", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Pod Count by Node",
   "type": "timeseries",
   "description": "Count the number of pods created in each node.",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "count by(node) (kube_pod_info)", "legendFormat": "{{node}}" }
   ]
  }
 ]
}