{
 "title": "Trimaran - LoadVariationRiskBalancing Plugin",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "10.242.64.4",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Node CPU Usage on 10.242.64.4",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "instance:node_cpu:ratio{instance=\"10.242.64.4\"}",
     "legendFormat": "CPU Load"
    },
    {
     "expr": "kube_node_status_allocatable{resource=\"cpu\", node=\"10.242.64.4\"}",
     "legendFormat": "CPU Allocatable"
    }
   ]
  },
  {
   "title": "10 Minute AVE",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg_over_time(instance:node_cpu:ratio{instance=\"10.242.64.4\"}[10m])",
     "legendFormat": "10.95.102.90"
    }
   ]
  },
  {
   "title": "10 Minute STD",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 11, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "stddev_over_time(instance:node_cpu:ratio{instance=\"10.242.64.4\"}[10m])",
     "legendFormat": "10.95.102.90"
    }
   ]
  },
  {
   "title": "10 Minute AVE + STD",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 13, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expression": "$A + $B", "type": "math" }
   ]
  },
  {
   "title": "Scheduled Testing Pods on 10.242.64.4",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{node=\"10.242.64.4\", resource=\"cpu\"})",
     "legendFormat": "Total CPU Requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\"})",
     "legendFormat": "Total CPU Limit"
    }
   ]
  },
  { "title": "10.242.64.5", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Node CPU Usage on 10.242.64.5",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "instance:node_cpu:ratio{instance=\"10.242.64.5\"}",
     "legendFormat": "CPU Load"
    },
    {
     "expr": "kube_node_status_allocatable{resource=\"cpu\", node=\"10.242.64.5\"}",
     "legendFormat": "CPU Allocatable"
    }
   ]
  },
  {
   "title": "10 Minute AVE",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 9, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg_over_time(instance:node_cpu:ratio{instance=\"10.242.64.5\"}[10m])",
     "legendFormat": "10.95.102.90"
    }
   ]
  },
  {
   "title": "10 Minute STD",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 11, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "stddev_over_time(instance:node_cpu:ratio{instance=\"10.242.64.5\"}[10m])",
     "legendFormat": "10.95.102.90"
    }
   ]
  },
  {
   "title": "10 Minute AVE + STD",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 13, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expression": "$A + $B", "type": "math" }
   ]
  },
  {
   "title": "Resource Allocation on 10.242.64.5",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{node=\"10.242.64.5\", resource=\"cpu\"})",
     "legendFormat": "Total CPU Requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\", node=\"10.242.64.5\"})",
     "legendFormat": "Total CPU Limit"
    }
   ]
  },
  { "title": "10.242.64.6", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Node CPU Usage on 10.242.64.6",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "instance:node_cpu:ratio{instance=\"10.242.64.6\"}",
     "legendFormat": "CPU Load"
    },
    {
     "expr": "kube_node_status_allocatable{resource=\"cpu\", node=\"10.242.64.6\"}",
     "legendFormat": "CPU Allocatable"
    }
   ]
  },
  {
   "title": "10 Minute AVE",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 9, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg_over_time(instance:node_cpu:ratio{instance=\"10.242.64.6\"}[10m])",
     "legendFormat": "10.95.102.90"
    }
   ]
  },
  {
   "title": "10 Minute STD",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 11, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "stddev_over_time(instance:node_cpu:ratio{instance=\"10.242.64.6\"}[10m])",
     "legendFormat": "10.95.102.90"
    }
   ]
  },
  {
   "title": "10 Minute AVE + STD",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 13, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expression": "$A + $B", "type": "math" }
   ]
  },
  {
   "title": "Scheduled Testing Pods on 10.242.64.4",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{node=\"10.242.64.6\", resource=\"cpu\"})",
     "legendFormat": "Total CPU Requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\", node=\"10.242.64.6\"})",
     "legendFormat": "Total CPU Limit"
    }
   ]
  }
 ]
}